version: "{build}"

skip_tags: true
test: off
max_jobs: 1

install:
  - cmd: cinst winflexbison
  - cmd: SET FLEXBISON_DIR=C:\ProgramData\chocolatey\lib\winflexbison\tools
  - cmd: SET MINGW_DIR=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1
  - cmd: SET PATH=%MINGW_DIR%\mingw32\bin;%FLEXBISON_DIR%;%PATH%
  - cmd: COPY %FLEXBISON_DIR%\win_flex.exe %FLEXBISON_DIR%\flex.exe
  - cmd: COPY %FLEXBISON_DIR%\win_bison.exe %FLEXBISON_DIR%\bison.exe

before_build:
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3
  - cmd: flex --version | head -1
  - cmd: bison --version | head -1

build_script:
  - cmd: mingw32-make -j1 --keep-going

after_build:
  - cmd: cd deploy
  - cmd: COPY ..\README.md .
  - cmd: COPY ..\LICENSE .
  - cmd: COPY ..\src\test.cpp .
  - cmd: 7z a ..\%APPVEYOR_PROJECT_NAME%-%APPVEYOR_BUILD_NUMBER%.7z .

artifacts:
  - path: $(appveyor_project_name)-$(appveyor_build_number).7z

deploy:
  - provider: Environment
    name: GH
    on:
      branch: master
